name: lifesync
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4
  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_database: #^10.5.5
  firebase_core:  #^2.31.0
  cloud_firestore:
  file_picker:
  #path_provider:
  provider:
  http:
  #animated_text_kit: ^4.2.2
  #gif_view: 0.3.1
  firebase_storage:
  cached_network_image: ^3.3.1
  gauge_indicator: ^0.4.3
  firebase_auth:
  blurrycontainer: ^2.1.0
  flutter_onboarding_slider: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

 
  fonts:
    - family: Roca
      fonts:
        - asset: fonts/Roca Black.ttf
          weight: 900
        - asset: fonts/Roca Bold.ttf
          weight: 700
        - asset: fonts/Roca Regular.ttf
          weight: 500 
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
