name: lifesync
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4
  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_database: #^10.5.5
  firebase_core:  #^2.31.0
  cloud_firestore:
  file_picker:
  #path_provider:
  provider:
  http:
  lottie: ^3.1.3
  #animated_text_kit: ^4.2.2
  #gif_view: 0.3.1
  firebase_storage:
  cached_network_image: ^3.3.1
  gauge_indicator: ^0.4.3
  firebase_auth:
  blurrycontainer: ^2.1.0
  #flutter_onboarding_slider: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/onboard_image_one.jpg
    - assets/onboardfour.jpg
    - assets/dp.jpg
    - assets/call.jpg
    - assets/lifesync.lottie

  fonts:
    - family: Roca
      fonts:
        - asset: fonts/Roca Black.ttf
          weight: 900
        - asset: fonts/Roca Bold.ttf
          weight: 700
        - asset: fonts/Roca Regular.ttf
          weight: 500 
          

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
